/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TripBy;

import org.junit.Test;
import org.testng.annotations.AfterTest;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
